feat: #1139: Manually publish donor update by donor ID
Anthony-Nolan/Atlas pull request #1148
Opened 2023-12-11 11:29 UTC by SergeyEzh

Couple notes for PR:

- I made regular static methods for creating SearchableDonorUpdate, because I find it more consistent as we can't have extension method for deletion update
- I wasn't sure about logging: where a failure should be logged? Do I need log the fact that manual publish updates was requested?

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)

2023-12-11 15:19 UTC, zabeen requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: all files reviewed, 14 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Helpers/SearchableDonorUpdateHelper.cs` line 13 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNpfap2KT9IM87QFiD:-NlNpfap2KT9IM87QFiE:b-r82cfq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Helpers/SearchableDonorUpdateHelper.cs#L13)):*
> ```Smalltalk
> namespace Atlas.DonorImport.Helpers
> {
>     public static class SearchableDonorUpdateHelper
> ```

Rename to `SearchableDonorUpdateMapper`



_Code quote:_
```Smalltalk
SearchableDonorUpdateHelper
```
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlOOqps4NPxIivTSvxK:-NlO7h5W7f3Gb-iMHlNh:b6ecsfa) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L16)):*
> ```Smalltalk
> namespace Atlas.DonorImport.Services
> {
>     public interface IManuallyPublishDonorUpdatesService
> ```

suggestion: move new method as an extension to existing interface, `IDonorUpdatesSaver`

and rename method to `GenerateAndSave(IEnumerable<int> donorIds)

because technically this service is not publishing any updates - that is taken care of by a separate scheduled workflow

rather, this new logic is an extension of the existing "Save" feature, with just one extra step of retrieving data from read repo



_Code quote:_
```Smalltalk
IManuallyPublishDonorUpdatesService
```
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 18 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNqKG1BSoBpuh23AhH:-NlNqKG1BSoBpuh23AhI:bd6tt9x) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L18)):*
> ```Smalltalk
>     public interface IManuallyPublishDonorUpdatesService
>     {
>         Task<bool> PublishDonorUpdates(int[] ids);
> ```

use `IEnumerable` or other suitable collection interface in method signatures - unless there is a specific need for an array?



_Code quote:_
```Smalltalk
int[]
```
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 24 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO895O33WVCNoFlAY-:-NlO895O33WVCNoFlAY0:bywzn0m) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L24)):*
> ```Smalltalk
>     public class ManuallyPublishDonorUpdatesService : IManuallyPublishDonorUpdatesService
>     {
>         private const int SaveBatchSize = 1500;
> ```

so after checking the code, I see this number lines up with the [const used in donor read repo](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs#L40).

maybe we should expose the repo const and use that instead? That way it is clear why we have chosen "1500" as our batch size



_Code quote:_
```Smalltalk
1500
```
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 41 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO6m5E6Mc7y8prrEfW:-NlO6m5E6Mc7y8prrEfX:b-f3w2pr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L41)):*
> ```Smalltalk
>             {
>                 var donorInfo = await donorReadRepository.GetDonorsByIds(ids);
>                 var updates = ids.Select(id => Convert(id, donorInfo)).ToList();
> ```

no need to enumerate here



_Code quote:_
```Smalltalk
ToList();
```
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 43 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO6Own4PKnqWBIMJDD:-NlO6Own4PKnqWBIMJDE:bsai45v) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L43)):*
> ```Smalltalk
>                 var updates = ids.Select(id => Convert(id, donorInfo)).ToList();
> 
>                 foreach (var batch in SplitIntoBatches(updates, SaveBatchSize))
> ```

Can use `MoreLinq` library `Batch` method instead

example usage: https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport/Services/DonorChecker/DonorIdChecker.cs#L57



_Code quote:_
```Smalltalk
SplitIntoBatches(updates, SaveBatchSize)
```
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 50 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlOR0hSEp0idk2QDxv4:-NlOR0hSEp0idk2QDxv5:bn0cf93) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L50)):*
> ```Smalltalk
>                 return true;
>             }
>             catch (Exception ex)
> ```

I don't think we need to catch and log the exception as it will automatically be written to Application Insights as an `exception` event
___
*[`Atlas.DonorImport.Functions/Functions/DonorImportFunctions.cs` line 93 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlONcvTBaANDbWStHHb:-NlONcvTBaANDbWStHHc:b-ykz59v) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Functions/Functions/DonorImportFunctions.cs#L93)):*
> ```Smalltalk
>             var ids = JsonConvert.DeserializeObject<int[]>(await reader.ReadToEndAsync());
> 
>             var succeed = await manuallyPublishDonorUpdatesService.PublishDonorUpdates(ids);
> ```

I don't think we need to return and process a `success` bool here

If no exception is thrown during function runtime, then framework will automatically return a success response

else on exception, it will automatically return `500`

so I suggest editing the `PublishDonorUpdates` signature to only return `Task`



_Code quote:_
```Smalltalk
var succeed
```
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 20 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO0kz07Gl856IyklYL:-NlO0kz07Gl856IyklYM:b-2gmfq2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs#L20)):*
> ```Smalltalk
> namespace Atlas.DonorImport.Test.Services
> {
>     [TestFixture]
> ```

Please apply the requested style changes to all affected tests, thanks
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 50 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNxNRx2p3f57hrI2Lg:-NlNxNRx2p3f57hrI2Lh:bi4p9f7) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs#L50)):*
> ```Smalltalk
> 
>         [Test]
>         public void PublishDonorUpdates_For_ExistingDonors()
> ```

Style: we usually end test names with expected outcome, which is helpful when a test fails during build, and also doubles as requirement documentation

 e.g., `PublishedDonorUpdates_ExistingDonors_SavesUpdateMessages`, `PublishDonorUpdates_NonExistingDonors_SaveDeletionMessages`



_Code quote:_
```Smalltalk
PublishDonorUpdates_For_ExistingDonors()
```
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 58 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNwZ03CO4ltHveVSoO:-NlNwZ03CO4ltHveVSoP:b-rp15tk) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.Dono [...]

2023-12-11 17:04 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: all files reviewed, 14 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlOOqps4NPxIivTSvxK:-NlOp6Kf57XY0EuAXGqG:bbm7zda) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L16)):*
<details><summary><i>Previously, SergeyEzh wrote…</i></summary><blockquote>

If you mean to add a new method to interface it will work, but tt can't be turned into extension method for the interface as method's logic uses additional dependency which DonorUpdatesSaver doesn't have nor expose.
</blockquote></details>

sorry for confusion: I didn't mean create an "extension" method. I meant delete interface `IManuallyPublishDonorUpdatesService`, and move the new code to existing interface, `IDonorUpdatesSaver`, as a new method on that interface called `GenerateAndSave`.


<!-- Sent from Reviewable.io -->

2023-12-12 13:25 UTC, SergeyEzh reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: all files reviewed, 14 unresolved discussions (waiting on @zabeen)

___
*[`Atlas.DonorImport/Helpers/SearchableDonorUpdateHelper.cs` line 13 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNpfap2KT9IM87QFiD:-NlT9v9h2774l0C_u9n5:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Helpers/SearchableDonorUpdateHelper.cs#L13)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Rename to `SearchableDonorUpdateMapper`
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlOOqps4NPxIivTSvxK:-NlT9wwJ9dKUJUpnuK2d:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L16)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

sorry for confusion: I didn't mean create an "extension" method. I meant delete interface `IManuallyPublishDonorUpdatesService`, and move the new code to existing interface, `IDonorUpdatesSaver`, as a new method on that interface called `GenerateAndSave`.
</blockquote></details>

Done.
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 18 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNqKG1BSoBpuh23AhH:-NlT9zpG5upkP1AP5ypl:b-m2f0kv) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L18)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

use `IEnumerable` or other suitable collection interface in method signatures - unless there is a specific need for an array?
</blockquote></details>

Changed to IEnumerable. Also I've changed existing Save method to receive IEnumrable, because ICollection's methods isn't used.
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 24 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO895O33WVCNoFlAY-:-NlTAM8L2sdwATIByCqb:b-jj9ue2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L24)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

so after checking the code, I see this number lines up with the [const used in donor read repo](https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport.Data/Repositories/DonorReadRepository.cs#L40).

maybe we should expose the repo const and use that instead? That way it is clear why we have chosen "1500" as our batch size
</blockquote></details>

I found out that PublishableDonorUpdatesRepository.BulkInsert saves data to database in batches so I think we don't need additional batching here.
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 41 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO6m5E6Mc7y8prrEfW:-NlTAwij9gwTc8XhXLvv:bqog7zb) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L41)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

no need to enumerate here
</blockquote></details>

Agree.
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 43 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO6Own4PKnqWBIMJDD:-NlTAzdU1VAHFMTQDCrJ:b-nhamah) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L43)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Can use `MoreLinq` library `Batch` method instead

example usage: https://github.com/Anthony-Nolan/Atlas/blob/master/Atlas.DonorImport/Services/DonorChecker/DonorIdChecker.cs#L57
</blockquote></details>

Removed it completely as I wrote above.
___
*[`Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs` line 50 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlOR0hSEp0idk2QDxv4:-NlTB76MA_tVZEVmzBnp:baglrut) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport/Services/ManuallyPublishDonorUpdatesService.cs#L50)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I don't think we need to catch and log the exception as it will automatically be written to Application Insights as an `exception` event
</blockquote></details>

Got it. Cleaned up.
___
*[`Atlas.DonorImport.Functions/Functions/DonorImportFunctions.cs` line 93 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlONcvTBaANDbWStHHb:-NlTBD6z01-BATq9meOb:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Functions/Functions/DonorImportFunctions.cs#L93)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I don't think we need to return and process a `success` bool here

If no exception is thrown during function runtime, then framework will automatically return a success response

else on exception, it will automatically return `500`

so I suggest editing the `PublishDonorUpdates` signature to only return `Task`
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 20 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlO0kz07Gl856IyklYL:-NlTBEVjDwxpER6bZEem:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs#L20)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Please apply the requested style changes to all affected tests, thanks
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 50 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNxNRx2p3f57hrI2Lg:-NlTBGem267_cpmA7i7e:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs#L50)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Style: we usually end test names with expected outcome, which is helpful when a test fails during build, and also doubles as requirement documentation

 e.g., `PublishedDonorUpdates_ExistingDonors_SavesUpdateMessages`, `PublishDonorUpdates_NonExistingDonors_SaveDeletionMessages`
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 58 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNwZ03CO4ltHveVSoO:-NlTBHcg7iZP4zGFv1dQ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9a6fc69c89032cf1047484db5ea507513effbcbd/Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs#L58)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

style: please add an empty line between act step and first assert step, especially as there are multiple asserts. It makes it much easier to read.
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/Services/ManuallyPublishDonorUpdatesServiceTest.cs` line 159 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlNswnZCiWNsbXx4mXu:-NlTBIgn5kUvdsHUTI9n:b-cxv1xb) ([raw file](https://git [...]

2023-12-12 15:27 UTC, zabeen requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: all files reviewed, 3 unresolved discussions (waiting on @SergeyEzh)

___
*[`Atlas.DonorImport/Services/DonorUpdates/DonorUpdatesSaver.cs` line 17 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTZmlnBf82MuAcSjs-:-NlTZmlo1UaO2vT3U9qp:b-bm7l5r) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9871fbbee87e3c5c4f9105e8599d5b24f767e6dc/Atlas.DonorImport/Services/DonorUpdates/DonorUpdatesSaver.cs#L17)):*
> ```Smalltalk
>     {
>         Task Save(IEnumerable<SearchableDonorUpdate> donorUpdates);
>         Task GenerateAndSave(IEnumerable<int> donorIds);
> ```

It would be good to add an XML comment documenting the generation behaviour: updates are generated for each id in `donorIds` before saving: an update message for id present in donor store, and deletion update for an absent id.
___
*[`Atlas.DonorImport.Test/TestHelpers/Builders/DatabaseDonorBuilder.cs` line 29 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTcNgx6-xy2BEGFaxD:-NlTcNgx6-xy2BEGFaxE:bmtbpnx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9871fbbee87e3c5c4f9105e8599d5b24f767e6dc/Atlas.DonorImport.Test/TestHelpers/Builders/DatabaseDonorBuilder.cs#L29)):*
> ```Smalltalk
>             .With(d => d.EthnicityCode, $"#{id}Eth")
>             .With(d => d.RegistryCode, $"#{id}RC")
>             .With(d => d.A_1, $"#{id}A_1")
> ```

I hope this is not nitpicking! but this code would be even more resilient to accidental typos if you used `$#{id}{nameof(d.prop)}` instead of typed out string values
___
*[`Atlas.DonorImport.Test/Services/DonorUpdates/DonorUpdatesSaveTests.cs` line 147 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTblbmAK4d516uRcQl:-NlTblbmAK4d516uRcQm:b-5nmbho) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9871fbbee87e3c5c4f9105e8599d5b24f767e6dc/Atlas.DonorImport.Test/Services/DonorUpdates/DonorUpdatesSaveTests.cs#L147)):*
> ```Smalltalk
>         private static readonly Dictionary<int, Data.Models.Donor> donorData = new Dictionary<int, Data.Models.Donor>
>         {
>             {1, DatabaseDonorBuilder.WithPropValuesBasedOnId(1, DatabaseDonorType.Adult)},
> ```

thanks, that is so much cleaner now! 

Only thing is, you may have to add `.Build()` to end of the builder method chain. I am not sure, it sometimes works without it, and sometimes doesn't!



_Code quote:_
```Smalltalk
DatabaseDonorBuilder.WithPropValuesBasedOnId(1, DatabaseDonorType.Adult)
```


<!-- Sent from Reviewable.io -->

2023-12-12 15:34 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: all files reviewed, 4 unresolved discussions (waiting on @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTdXjC4JH3gdhNnCoL:-NlTdXjC4JH3gdhNnCoM:bpe3zmo) (no related file):*
Changes look really good, thanks for that.

Please can you add some key integration tests to [Atlas.DonorImport.Test.Integration/IntegrationTests/DonorUpdates](https://github.com/Anthony-Nolan/Atlas/tree/master/Atlas.DonorImport.Test.Integration/IntegrationTests/DonorUpdates) namespace, as this feature is heavily reliant on reading and writing from and to the db.

___


<!-- Sent from Reviewable.io -->

2023-12-13 11:32 UTC, SergeyEzh reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: all files reviewed, 4 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTdXjC4JH3gdhNnCoL:-NlXweD047W6JMRJBoDu:b-896fix) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Changes look really good, thanks for that.

Please can you add some key integration tests to [Atlas.DonorImport.Test.Integration/IntegrationTests/DonorUpdates](https://github.com/Anthony-Nolan/Atlas/tree/master/Atlas.DonorImport.Test.Integration/IntegrationTests/DonorUpdates) namespace, as this feature is heavily reliant on reading and writing from and to the db.
</blockquote></details>

Done.

___
___
*[`Atlas.DonorImport/Services/DonorUpdates/DonorUpdatesSaver.cs` line 17 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTZmlnBf82MuAcSjs-:-NlTi8VJ-N9i_NmR3Bpn:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9871fbbee87e3c5c4f9105e8599d5b24f767e6dc/Atlas.DonorImport/Services/DonorUpdates/DonorUpdatesSaver.cs#L17)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

It would be good to add an XML comment documenting the generation behaviour: updates are generated for each id in `donorIds` before saving: an update message for id present in donor store, and deletion update for an absent id.
</blockquote></details>

Done.
___
*[`Atlas.DonorImport.Test/TestHelpers/Builders/DatabaseDonorBuilder.cs` line 29 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTcNgx6-xy2BEGFaxD:-NlTiumlD1MZrK8OsNtS:b528vm6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9871fbbee87e3c5c4f9105e8599d5b24f767e6dc/Atlas.DonorImport.Test/TestHelpers/Builders/DatabaseDonorBuilder.cs#L29)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I hope this is not nitpicking! but this code would be even more resilient to accidental typos if you used `$#{id}{nameof(d.prop)}` instead of typed out string values
</blockquote></details>

Personally, I don't think that it is a big deal as tests show us if there's any type. But it is no problem to rewrite it as you want.
___
*[`Atlas.DonorImport.Test/Services/DonorUpdates/DonorUpdatesSaveTests.cs` line 147 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148#-NlTblbmAK4d516uRcQl:-NlTiBzeETW0Rtov1z64:b4abkfl) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/9871fbbee87e3c5c4f9105e8599d5b24f767e6dc/Atlas.DonorImport.Test/Services/DonorUpdates/DonorUpdatesSaveTests.cs#L147)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

thanks, that is so much cleaner now! 

Only thing is, you may have to add `.Build()` to end of the builder method chain. I am not sure, it sometimes works without it, and sometimes doesn't!
</blockquote></details>

In my case it worked because of implicit operator overload for `Builder<>`. But I added .`Build()` for clarity


<!-- Sent from Reviewable.io -->

2023-12-13 11:54 UTC, zabeen approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1148)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SergeyEzh)



<!-- Sent from Reviewable.io -->

2023-12-13 13:31 UTC, merged