feature: #1357: HLA metadata dictionary sliding cache
Anthony-Nolan/Atlas pull request #1364
Opened 2024-08-27 13:36 UTC by SergeyEzh

2024-08-29 08:57 UTC, daria-sorokina-da requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364)* status: all files reviewed, 1 unresolved discussion (waiting on @pchenery and @SergeyEzh)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O5SLThP41THlEj9a5kv:-O5SLThP41THlEj9a5kw:b-8oxe5o) (no related file):*
Need to update terraform of all affected apps, and add a new variable there

___


<!-- Sent from Reviewable.io -->

2024-09-09 15:37 UTC, daria-sorokina-da requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364)* status: all files reviewed, 22 unresolved discussions (waiting on @pchenery and @SergeyEzh)

___
*[`Atlas.Functions/local.settings.template.json` line 60 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MOvFC9Zj4xjhIZt2V:-O6MOvFC9Zj4xjhIZt2W:b-ok38vr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.Functions/local.settings.template.json#L60)):*
> ```JSON
>     "NotificationsServiceBus:NotificationsTopic": "notifications",
> 
>     "SearchRelatedMetadataServices:CacheSlidingExpirationInSeconds": 300
> ```

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
___
*[`Atlas.MatchingAlgorithm.Functions/local.settings.template.json` line 50 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPEwt7Md_dHe__S9N:-O6MPEwt7Md_dHe__S9O:b-ok38vr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.MatchingAlgorithm.Functions/local.settings.template.json#L50)):*
> ```JSON
>     "NotificationsServiceBus:ConnectionString": "override-this",
>     "NotificationsServiceBus:NotificationsTopic": "notifications",
>     "SearchRelatedMetadataServices:CacheSlidingExpirationInSeconds": 300,
> ```

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
___
*[`Atlas.MatchPrediction.Functions/local.settings.template.json` line 22 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPIqUE4ItDIBLXa7J:-O6MPIqUE4ItDIBLXa7K:b-ok38vr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.MatchPrediction.Functions/local.settings.template.json#L22)):*
> ```JSON
>     "NotificationsServiceBus:ConnectionString": "override-this",
>     "NotificationsServiceBus:NotificationsTopic": "notifications",
>     "SearchRelatedMetadataServices:CacheSlidingExpirationInSeconds": 300
> ```

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
___
*[`Atlas.RepeatSearch.Functions/local.settings.template.json` line 27 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPMn40MbzbExbQ65-:-O6MPMn40MbzbExbQ650:b-ok38vr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.RepeatSearch.Functions/local.settings.template.json#L27)):*
> ```JSON
>     "NotificationsServiceBus:ConnectionString": "override-this",
>     "NotificationsServiceBus:NotificationsTopic": "notifications",
>     "SearchRelatedMetadataServices:CacheSlidingExpirationInSeconds": 300
> ```

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
___
*[`terraform/core/function.tf` line 84 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MOeYK0YGlRfrV82LN:-O6MOeYL0Cjk8wXZuVB8:burnzwo) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/function.tf#L84)):*
> ```HCL
>     "MatchPrediction:AzureStorage:MatchPredictionResultsBlobContainer" = module.match_prediction.storage.match_prediction_results_container_name
> 
>     "SearchRelatedMetadataServices:CacheSlidingExpirationInSeconds" = var.ATLAS_FUNCTION_HLA_CACHE_SLIDING_EXPIRATION_SEC,
> ```

Let's change the variable name to 

`ATLAS_FUNCTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
___
*[`terraform/core/function.tf` line 84 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPPbrBJ5C-8QguzML:-O6MPPbrBJ5C-8QguzMM:b-ok38vr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/function.tf#L84)):*
> ```HCL
>     "MatchPrediction:AzureStorage:MatchPredictionResultsBlobContainer" = module.match_prediction.storage.match_prediction_results_container_name
> 
>     "SearchRelatedMetadataServices:CacheSlidingExpirationInSeconds" = var.ATLAS_FUNCTION_HLA_CACHE_SLIDING_EXPIRATION_SEC,
> ```

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
___
*[`terraform/core/main.tf` line 149 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPfAv0ZCzPFDjeXnd:-O6MPfAv0ZCzPFDjeXne:b-ykvekb) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/main.tf#L149)):*
> ```HCL
>   WEBSITE_RUN_FROM_PACKAGE                         = var.WEBSITE_RUN_FROM_PACKAGE
>   WMDA_FILE_URL                                    = var.WMDA_FILE_URL
>   HLA_CACHE_SLIDING_EXPIRATION_SEC                 = var.MATCHING_ALGORITHM_HLA_CACHE_SLIDING_EXPIRATION_SEC
> ```

Let's change the variable name to 

`SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC  = var.MATCHING_ALGORITHM_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
___
*[`terraform/core/main.tf` line 191 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPvthD8dQuUdtk-lt:-O6MPvthD8dQuUdtk-lu:bmaax7l) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/main.tf#L191)):*
> ```HCL
>   MAC_SOURCE                       = var.MAC_SOURCE
>   WEBSITE_RUN_FROM_PACKAGE         = var.WEBSITE_RUN_FROM_PACKAGE
>   HLA_CACHE_SLIDING_EXPIRATION_SEC = var.MATCH_PREDICTION_HLA_CACHE_SLIDING_EXPIRATION_SEC
> ```

Let's change the variable name to 

`SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC  = var.MATCH_PREDICTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
___
*[`terraform/core/main.tf` line 246 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPyRMBtzIMnxzF1JD:-O6MPyRMBtzIMnxzF1JE:br715jm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/main.tf#L246)):*
> ```HCL
>   REPEAT_SEARCH_RESULTS_READY_SUBSCRIPTION_NAMES = var.SEARCH_RESULTS_READY_SUBSCRIPTION_NAMES
>   RESULTS_BATCH_SIZE                             = var.RESULTS_BATCH_SIZE
>   HLA_CACHE_SLIDING_EXPIRATION_SEC               = var.REPEAT_SEARCH_HLA_CACHE_SLIDING_EXPIRATION_SEC
> ```

Let's change the variable name to 

`SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC  = var.REPEAT_SEARCH_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
___
*[`terraform/core/variables.tf` line 421 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ1IYDuDzh2Mdo18Y:-O6MQ1IZCpX0MnoBho1-:b-q3i0zk) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/variables.tf#L421)):*
> ```HCL
> }
> 
> variable "ATLAS_FUNCTION_HLA_CACHE_SLIDING_EXPIRATION_SEC" {
> ```

ATLAS_FUNCTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC
___
*[`terraform/core/variables.tf` line 427 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ5Hk9rRTVFqWMmSX:-O6MQ5Hk9rRTVFqWMmSY:b-f72jwh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/variables.tf#L427)):*
> ```HCL
> }
> 
> variable "MATCHING_ALGORITHM_HLA_CACHE_SLIDING_EXPIRATION_SEC" {
> ```

MATCHING_ALGORITHM_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC
___
*[`terraform/core/variables.tf` line 433 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ79T0KS14MAGltSM:-O6MQ79T0KS14MAGltSN:b-5sjpb1) ([raw file](https://github.com/Anthony- [...]

2024-09-10 09:32 UTC, SergeyEzh reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364)* status: all files reviewed, 22 unresolved discussions (waiting on @daria-sorokina-da and @pchenery)

___
*[`Atlas.Functions/local.settings.template.json` line 60 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MOvFC9Zj4xjhIZt2V:-O6QGUpx8YFN8sI9MfDQ:bgnr93d) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.Functions/local.settings.template.json#L60)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
</blockquote></details>

Do you want to add `SearchRelatedMetadata` property to `HlaMetadataDictionarySettings` class as well?


<!-- Sent from Reviewable.io -->

2024-09-11 14:08 UTC, SergeyEzh reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364)* status: 2 of 39 files reviewed, 22 unresolved discussions (waiting on @daria-sorokina-da and @pchenery)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O5SLThP41THlEj9a5kv:-O6WOUnsD_Pn6niBLTmd:bb7f2mf) (no related file):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Need to update terraform of all affected apps, and add a new variable there
</blockquote></details>

done

___
___
*[`Atlas.MatchingAlgorithm.Functions/local.settings.template.json` line 50 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPEwt7Md_dHe__S9N:-O6WOdQm03Y0jkmZnf4V:bb7f2mf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.MatchingAlgorithm.Functions/local.settings.template.json#L50)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
</blockquote></details>

done
___
*[`Atlas.MatchPrediction.Functions/local.settings.template.json` line 22 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPIqUE4ItDIBLXa7J:-O6WOf0h3jWRRhqEmCnb:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.MatchPrediction.Functions/local.settings.template.json#L22)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
</blockquote></details>

Done.
___
*[`Atlas.RepeatSearch.Functions/local.settings.template.json` line 27 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPMn40MbzbExbQ65-:-O6WOfcgD3P9B5sZNV2U:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/Atlas.RepeatSearch.Functions/local.settings.template.json#L27)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
</blockquote></details>

Done.
___
*[`terraform/core/function.tf` line 84 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MOeYK0YGlRfrV82LN:-O6WOhYiCVc1eDV4d1hH:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/function.tf#L84)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the variable name to 

`ATLAS_FUNCTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
</blockquote></details>

Done.
___
*[`terraform/core/function.tf` line 84 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPPbrBJ5C-8QguzML:-O6WOhqd69ergBKpsnGr:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/function.tf#L84)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the prefix of this setting in all places to HlaMetadataDictionary:SearchRelatedMetadata:CacheSlidingExpirationInSeconds and place it near other "HlaMetadataDictionary" settings above
</blockquote></details>

Done.
___
*[`terraform/core/main.tf` line 149 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPfAv0ZCzPFDjeXnd:-O6WOicc2paUUHhqsBEt:bb6un1j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/main.tf#L149)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the variable name to 

`SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC  = var.MATCHING_ALGORITHM_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
</blockquote></details>

Done
___
*[`terraform/core/main.tf` line 191 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPvthD8dQuUdtk-lt:-O6WOwkD7b7UmOiYWWxf:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/main.tf#L191)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the variable name to 

`SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC  = var.MATCH_PREDICTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
</blockquote></details>

Done.
___
*[`terraform/core/main.tf` line 246 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MPyRMBtzIMnxzF1JD:-O6WOz9u9aBRla-smwgu:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/main.tf#L246)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the variable name to 

`SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC  = var.REPEAT_SEARCH_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC`
</blockquote></details>

Done.
___
*[`terraform/core/variables.tf` line 421 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ1IYDuDzh2Mdo18Y:-O6WPFqV2JxcY-SkZbd6:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/variables.tf#L421)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

ATLAS_FUNCTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC
</blockquote></details>

Done.
___
*[`terraform/core/variables.tf` line 427 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ5Hk9rRTVFqWMmSX:-O6WPGDcD95LeVBwLbaJ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/variables.tf#L427)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

MATCHING_ALGORITHM_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC
</blockquote></details>

Done.
___
*[`terraform/core/variables.tf` line 433 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ79T0KS14MAGltSM:-O6WPIz6EkhazXEKk2yQ:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/variables.tf#L433)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

MATCH_PREDICTION_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC
</blockquote></details>

Done.
___
*[`terraform/core/variables.tf` line 439 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQ9bf9ZyiNbyhYcMC:-O6WPJR3D_EomkWCPWZa:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/variables.tf#L439)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

REPEAT_SEARCH_SEARCH_RELATED_HLA_METADATA_CACHE_SLIDING_EXPIRATION_SEC
</blockquote></details>

Done.
___
*[`terraform/core/modules/match_prediction/function.tf` line 41 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364#-O6MQHMS5GwqW0oFmJKG:-O6WPLKx5e_qmH2Jnr7K:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3042f7e39a7cc55261951d0441060a2b710c4966/terraform/core/modules/match_prediction/function.tf#L41)):*
<details><summary><i>Previously, daria-sorokina-da (Daria Sorokina) wrote…</i></summary><blockquote>

Let's change the variable name to 

`SEARCH_RELATED_ [...]

2024-09-12 08:45 UTC, daria-sorokina-da approved these changes
> Reviewed 37 of 37 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/1364)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pchenery)



<!-- Sent from Reviewable.io -->

2024-09-12 08:46 UTC, merged