897 out of memory exception thrown when large resultsets serialized
Anthony-Nolan/Atlas pull request #913
Opened 2023-03-20 04:56 UTC by IgorKupreychik

2023-03-20 13:49 UTC, zabeen requested changes
> Reviewed 31 of 31 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 32 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Client.Models/Search/Results/ResultsNotification.cs` line 31 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyprp25QZSsSzM1Uea:-NQyprp25QZSsSzM1Ueb:bwdizmn) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L31)):*
> ```Smalltalk
>         public string MatchingAlgorithmHlaNomenclatureVersion { get; set; }
> 
>         public bool ResultBatched { get; set; }
> ```

small rename: `ResultsBatched`



_Code quote:_
```Smalltalk
ResultBatched
```
___
*[`Atlas.Client.Models/Search/Results/ResultsNotification.cs` line 31 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQypzA017STY3RX-YzB:-NQypmn07JquWR2rDOEz:bk1uhwk) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L31)):*
> ```Smalltalk
>         public string MatchingAlgorithmHlaNomenclatureVersion { get; set; }
> 
>         public bool ResultBatched { get; set; }
> ```

Please add doccomments for the 2 new props, including fact that `BatchFolder` will be empty if results were not batched
___
*[`Atlas.Client.Models/Search/Results/ResultsNotification.cs` line 33 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyQXmwAddPQFvcq8pC:-NQyQXmwAddPQFvcq8pD:bqp65ew) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L33)):*
> ```Smalltalk
>         public bool ResultBatched { get; set; }
> 
>         public string BatchFolder { get; set; }
> ```

`BatchFolderName`
___
*[`Atlas.Client.Models/Search/Results/ResultSet/BatchedResultSet.cs` line 10 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyS1bgBR0_eOFQ9ACP:-NQyS1bgBR0_eOFQ9ACQ:bntdznt) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Client.Models/Search/Results/ResultSet/BatchedResultSet.cs#L10)):*
> ```Smalltalk
> 
>         [JsonIgnore]
>         public bool BatchedResult { get; set; } = true;
> ```

is there a reason this could not be added to the `ResultSet<T>` base class, with default as `false`, and then there is no need for this new base class?
___
*[`Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs` line 54 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQzAVpnA9IU2BRh7W6x:-NQySLjp3khletxsxWDy:b-lbfl06) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs#L54)):*
> ```Smalltalk
>         public IEnumerable<TResult> Results { get; set; }
> 
>         public virtual bool ShouldSerializeResults() => true;
> ```

is this leveraging: https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm

I've not seen this before (had to look it up). Could you please add a doccomment about it.
___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 13 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyT9nB0WL-9-86Bu5U:-NQyT9nB0WL-9-86Bu5V:b88qqwk) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L13)):*
> ```Smalltalk
>     {
>         Task<T> Download<T>(string container, string filename);
>         Task<IEnumerable<T>> BatchDownload<T>(string container, string folderName);
> ```

Suggest rename to `DownloadFolderContents`
___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 48 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyTjMk-kHgZE9N_kQv:-NQyTjMk-kHgZE9N_kQw:b4c9lyr) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L48)):*
> ```Smalltalk
> 
>             var containerClient = GetBlobContainer(container);
>             var blobs =  containerClient.GetBlobsAsync(prefix: $"{folderName}/");
> ```

:thumbsup: 
___
*[`Atlas.Common/AzureStorage/Blob/BlobUploader.cs` line 38 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyVcuL2GpbMu1mb2Q_:-NQyVcuM3QfwZkBWK0Q_:b-7nhu34) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Common/AzureStorage/Blob/BlobUploader.cs#L38)):*
> ```Smalltalk
>         public async Task BatchUpload<T>(IEnumerable<T> list, int batchSize, string blobContainer, string blobFolder)
>         {
>             var azureStorageEventModel = new AzureStorageEventModel(blobFolder, blobContainer);
> ```

could move these lines and the `SendEvent` lines to base class, as they are used in multiple methods.



_Code quote:_
```Smalltalk
            var azureStorageEventModel = new AzureStorageEventModel(blobFolder, blobContainer);
            azureStorageEventModel.StartAzureStorageCommunication();
```
___
*[`Atlas.Common/AzureStorage/Blob/BlobUploader.cs` line 47 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQyXDnu65KCC5yVyd0L:-NQyXDnu65KCC5yVyd0M:b6agbj2) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Common/AzureStorage/Blob/BlobUploader.cs#L47)):*
> ```Smalltalk
>             {
>                 var serializedBatch = JsonConvert.SerializeObject(batch);
>                 await UploadBlob(containerClient, $"{blobFolder}/{++batchNumber}.json", serializedBatch);
> ```

FYI: this is fine for now, but for  #908, I'd like this method to be commonised for use in batching of match prediction requests. But there, [a different naming convention is used for each file](https://github.com/Anthony-Nolan/Atlas/blob/761ce4fed5b94917d8b2ef830e8e37d41619cbef/Atlas.Functions/Services/BlobStorageClients/MatchPredictionRequestBlobClient.cs#L31). Nothing to worry about here, just a heads up :)



_Code quote:_
```Smalltalk
$"{blobFolder}/{++batchNumber}.json"
```
___
*[`Atlas.Functions/local.settings.template.json` line 14 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQykWmxAYuWSMnJUkNN:-NQykWmxAYuWSMnJUkNO:b-7kgjif) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Functions/local.settings.template.json#L14)):*
> ```JSON
>     "AtlasFunction:AzureStorage:MatchPredictionRequestsBlobContainer": "match-prediction-requests",
>     "AtlasFunction:AzureStorage:MatchPredictionResultsBlobContainer": "match-prediction-results",
>     "AtlasFunction:AzureStorage:BatchSize": 10000,
> ```

pls set to `0` to be consistent with default terraform value
___
*[`Atlas.Functions/local.settings.template.json` line 14 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQykhSF1wzJyROrQm0U:-NQykhSF1wzJyROrQm0V:b-635glx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Functions/local.settings.template.json#L14)):*
> ```JSON
>     "AtlasFunction:AzureStorage:MatchPredictionRequestsBlobContainer": "match-prediction-requests",
>     "AtlasFunction:AzureStorage:MatchPredictionResultsBlobContainer": "match-prediction-results",
>     "AtlasFunction:AzureStorage:BatchSize": 10000,
> ```

Please name it more clearly, e.g., `SearchResultsBatchSize`
___
*[`Atlas.Functions/Services/BlobStorageClients/MatchingResultsDownloader.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQymMfg8u0H7jTSXkGG:-NQymMfg8u0H7jTSXkGH:b-sovor6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Functions/Services/BlobStorageClients/MatchingResultsDownloader.cs#L16)):*
> ```Smalltalk
>     public interface IMatchingResultsDownloader
>     {
>         public Task [...]

2023-03-20 14:18 UTC, IgorKupreychik commented
*[`Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs` line 54 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQzAVpnA9IU2BRh7W6x:-NQzNR13DR-m3XA7XCsP:b13jpdw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Client.Models/Search/Results/ResultSet/ResultSet.cs#L54)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

is this leveraging: https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm

I've not seen this before (had to look it up). Could you please add a doccomment about it.
</blockquote></details>

Right, it's used to control if we need to serialize results or not. I'll add a doccomment.


<!-- Sent from Reviewable.io -->

2023-03-21 17:23 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 34 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 52 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NR42MQ6A3fHQaVjxKfi:-NR4BN-428EyJ-DVqPnN:b-npmfwz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2510dbeba20740bf0ae76d0e6c9532dbc7118f89/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L52)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

after seeing some memory usage stats for repeat search today, I think we should amend this to `yield return` a single blob (i.e., `IAsyncEnumerable<T>`) and have repeat search store one blob's worth of results at a time.

This method is also used by search orchestrator to download results before match prediction... I think it's worth doing the same thing there to avoid having all results in memory.

I advise first doing the minor review markups, and then doing `yield return` refactor afterwards as a `refactor:` commit
</blockquote></details>

re: search orchestrator download, there is a complication there where we group donors by HLA typing and ethnicity/registry before batching the match prediction requests. Let's talk about it over a call when you are back


<!-- Sent from Reviewable.io -->

2023-03-22 12:03 UTC, zabeen reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 33 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 52 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NR42MQ6A3fHQaVjxKfi:-NR8Ag6O4N0glMHBxxuF:bysxvo5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/2510dbeba20740bf0ae76d0e6c9532dbc7118f89/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L52)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

re: search orchestrator download, there is a complication there where we group donors by HLA typing and ethnicity/registry before batching the match prediction requests. Let's talk about it over a call when you are back
</blockquote></details>

agreed to move this change to a new ticket


<!-- Sent from Reviewable.io -->

2023-03-22 12:16 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 33 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Functions/Services/BlobStorageClients/MatchingResultsDownloader.cs` line 16 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQymMfg8u0H7jTSXkGG:-NR8Ehz1ACJSfI51e2LT:bj2bmcf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.Functions/Services/BlobStorageClients/MatchingResultsDownloader.cs#L16)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

I think it would be clearer contract if there were two methods: `Download` and `DownloadBatchFolder` 
</blockquote></details>

agreed to make `batchFolder` param nullable and add docomment to interface method to explain behaviour when param `null` or not `null`


<!-- Sent from Reviewable.io -->

2023-03-22 13:22 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 31 unresolved discussions (waiting on @IgorKupreychik)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NR8SSdhAlzlXInap-uQ:-NR8U2SJCPIIo_NpdCmG:bjx5b2j) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

reminder to update config readme with info on new terraform release var for result batch size:
https://github.com/Anthony-Nolan/Atlas/blob/master/README_Configuration.md#performance--scale-tuning

Recommend adding a new sub-heading "Search Results" under the "Performance" section
</blockquote></details>

Will also need to update Integration docs about the new batching results functionality:
https://github.com/Anthony-Nolan/Atlas/blob/master/README_Integration.md#receiving-search-results

___


<!-- Sent from Reviewable.io -->

2023-03-23 15:27 UTC, zabeen requested changes
> Reviewed 34 of 34 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 11 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Client.Models/Search/Results/ResultsNotification.cs` line 37 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRE3yJb8hz3L--A2ul_:-NRE3yJb8hz3L--A2ula:b-ansp8i) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Client.Models/Search/Results/ResultsNotification.cs#L37)):*
> ```Smalltalk
>         public bool ResultsBatched { get; set; }
> 
>         /// <summary>
> ```

nitpick: use `<see cref="ResultsBatched" />`



_Code quote:_
```Smalltalk
ResultsBatched
```
___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 17 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDUlx6B1i7xJCbezUl:-NRDUlx6B1i7xJCbezUm:buckwx6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L17)):*
> ```Smalltalk
>     public class BlobDownloader : AzureStorageBlobClient, IBlobDownloader
>     {
>         private const string DownloadLogLabel = "Download";
> ```

This private `LogLabel` field should be moved to base class `AzureStorageBlobClient`, and then set its value via `base()` constructor parameter. As it's only being used by the now base method, `EndAzureStorageCommunication()`.
___
*[`Atlas.Common/AzureStorage/Blob/BlobUploader.cs` line 14 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDV_WI-IiRxcYKuQyn:-NRDV_WI-IiRxcYKuQyo:beoa7f0) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Common/AzureStorage/Blob/BlobUploader.cs#L14)):*
> ```Smalltalk
>     public class BlobUploader : AzureStorageBlobClient
>     {
>         private const string UploadLogLabel = "Upload";
> ```

same comment as above, re: move to `Client` base class
___
*[`Atlas.Common/AzureStorage/Blob/BlobUploader.cs` line 16 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDVkO37BXBqwFVJhZi:-NRDVkO37BXBqwFVJhZj:b-uu3jit) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Common/AzureStorage/Blob/BlobUploader.cs#L16)):*
> ```Smalltalk
>         private const string UploadLogLabel = "Upload";
> 
>         public ILogger Logger { get; }
> ```

why is this a public read-only prop? is it still needed here?
___
*[`Atlas.Functions/Services/BlobStorageClients/MatchingResultsDownloader.cs` line 33 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDWE8o7Hgw0qyWDvcV:-NRDWE8o7Hgw0qyWDvcW:b-1ac12i) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Functions/Services/BlobStorageClients/MatchingResultsDownloader.cs#L33)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// if "batchFolder" is not null, results will be loaded from all files within this folder, otherwise - results will be loaded along with search summary from "blobName" file
> ```

comment is great, but please move to above the interface method
___
*[`Atlas.MatchingAlgorithm/Clients/AzureStorage/ResultsBlobStorageClient.cs` line 29 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDjvvs143OZagG9qbT:-NRDjvvs143OZagG9qbU:b-ujiqsm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.MatchingAlgorithm/Clients/AzureStorage/ResultsBlobStorageClient.cs#L29)):*
> ```Smalltalk
>         public async Task UploadResults(ResultSet<MatchingAlgorithmResult> searchResultSet)
>         {
>             searchResultSet.BatchedResult = azureStorageSettings.ShouldBatchResults;  // Results will not be serialised if results are being batched
> ```

nitpick: add a newline before comment pls
___
*[`Atlas.RepeatSearch/Clients/AzureStorage/RepeatSearchResultsBlobStorageClient.cs` line 31 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDkhRV0ehGW9-S-TIS:-NRDkhRV0ehGW9-S-TIT:bpjdeji) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.RepeatSearch/Clients/AzureStorage/RepeatSearchResultsBlobStorageClient.cs#L31)):*
> ```Smalltalk
>         public async Task UploadResults(RepeatMatchingAlgorithmResultSet repeatSearchResultSet)
>         {
>             repeatSearchResultSet.BatchedResult = azureStorageSettings.ShouldBatchResults;  // Results will not be serialised if results are being batched
> ```

nitpick, as above, pls add newline before comment


<!-- Sent from Reviewable.io -->

2023-03-23 16:38 UTC, IgorKupreychik commented
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 17 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDUlx6B1i7xJCbezUl:-NREHb-B2W4XBCfuVvpG:b16nub3) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L17)):*
> EndAzureStorageCommunication
It will affect BlobStreamer class, which doesn't log anything at the moment... If you're okay with it - would "Stream" log lable be okay for this class?


<!-- Sent from Reviewable.io -->

2023-03-24 10:23 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: 34 of 42 files reviewed, 9 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/BlobDownloader.cs` line 17 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDUlx6B1i7xJCbezUl:-NRI8H9S8Jc5bBlteWSd:b-i8pmgm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Common/AzureStorage/Blob/BlobDownloader.cs#L17)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

> EndAzureStorageCommunication
It will affect BlobStreamer class, which doesn't log anything at the moment... If you're okay with it - would "Stream" log lable be okay for this class?
</blockquote></details>

that's fine to use `Stream` as log label


<!-- Sent from Reviewable.io -->

2023-03-24 10:27 UTC, zabeen requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Common/AzureStorage/Blob/BlobUploader.cs` line 16 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRDVkO37BXBqwFVJhZi:-NRI8b_80vK6JcLEixBI:b-kfa9jp) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/756a76c34de903a62722d70a588e52a00dad0729/Atlas.Common/AzureStorage/Blob/BlobUploader.cs#L16)):*
<details><summary><i>Previously, IgorKupreychik wrote…</i></summary><blockquote>

It's used by child classes of BlobUploader, I'll update the access modifier to 'protected' 
</blockquote></details>

sorry to drag this out! but do we need two base class references to the same ILogger instance? might be better to remove this, and make the ILogger in `BlobClient` base class protected instead?
___
*[`terraform/core/variables.tf` line 339 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRI9ApJ6VNBUuhKILW7:-NRI9ApJ6VNBUuhKILW8:b-d6oa9j) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/terraform/core/variables.tf#L339)):*
> ```HCL
>   type        = number
>   default     = 0
>   description = "Batch size (number of donors for one batch) for saving search/matching results"
> ```

number of results written per file



_Code quote:_
```HCL
number of donors for one batch
```


<!-- Sent from Reviewable.io -->

2023-03-24 10:41 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 7 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.Functions/Services/BlobStorageClients/ResultsUploader.cs` line 19 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRIBpYv-aHOiACppq2Y:-NRIBpYv-aHOiACppq2Z:b-pi9d9n) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/Atlas.Functions/Services/BlobStorageClients/ResultsUploader.cs#L19)):*
> ```Smalltalk
>     internal class ResultsUploader : BlobUploader, IResultsUploader
>     {
>         private readonly AzureStorageSettings azureStorageSettings;
> ```

remove this
___
*[`Atlas.Functions/Services/BlobStorageClients/ResultsUploader.cs` line 33 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRIBmzi5DmTpDZnrMnb:-NRIADWf8Z6GzcWyyRKF:b-mu0t41) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/Atlas.Functions/Services/BlobStorageClients/ResultsUploader.cs#L33)):*
> ```Smalltalk
>             using (Logger.RunTimed($"Uploading results: {searchResultSet.SearchRequestId}"))
>             {
>                 searchResultSet.BatchedResult = azureStorageSettings.ShouldBatchResults;
> ```

remove this line
___
*[`Atlas.Functions/Services/BlobStorageClients/ResultsUploader.cs` line 38 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRIBtPe8MwQCpZ1rDz9:-NRIBtPe8MwQCpZ1rDzA:bquac5d) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/Atlas.Functions/Services/BlobStorageClients/ResultsUploader.cs#L38)):*
> ```Smalltalk
>                 await Upload(container, searchResultSet.ResultsFileName, serialisedResults);
> 
>                 if (azureStorageSettings.ShouldBatchResults)
> ```

change to `searchResultSet.BatchedResult`



_Code quote:_
```Smalltalk
azureStorageSettings.ShouldBatchResults
```
___
*[`Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs` line 89 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRIBhhSCcEQl_zlhL3L:-NRIBhhSCcEQl_zlhL3M:bny5x7h) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/Atlas.MatchingAlgorithm/Services/Search/SearchRunner.cs#L89)):*
> ```Smalltalk
>                     MatchingAlgorithmHlaNomenclatureVersion = hlaNomenclatureVersion,
>                     BlobStorageContainerName = blobContainerName,
>                     SearchRequest = identifiedSearchRequest.SearchRequest
> ```

reminder, set ResultsBatched to true/false here
___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs` line 80 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQzE9uZ3iLrHimvbLUj:-NRI9MBC2dB6xLZZT5Xc:b-wgdqh4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs#L80)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

would be good to assert the value of `ResultsBatched` prop - both when Results are batched and results are not batched, as you did for notification tests.
</blockquote></details>

still missing the extra tests for asserting the new `ResultsBatched` prop on the `ResultSet<>` arg


<!-- Sent from Reviewable.io -->

2023-03-24 10:42 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 8 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs` line 109 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRICTTf5sHrIGhlYumI:-NRICTTf5sHrIGhlYumJ:bnejjt0) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/Atlas.RepeatSearch/Services/Search/RepeatSearchRunner.cs#L109)):*
> ```Smalltalk
>                     MatchingAlgorithmHlaNomenclatureVersion = hlaNomenclatureVersion,
>                     BlobStorageContainerName = blobContainerName,
>                     NoLongerMatchingDonors = diff.RemovedResults.ToList()
> ```

set `ResultsBatched` here too


<!-- Sent from Reviewable.io -->

2023-03-24 11:21 UTC, zabeen reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

___
*[`Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs` line 80 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NQzE9uZ3iLrHimvbLUj:-NRILPegAmAMJsBLeIVf:bgfg2en) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/349901d598a6e04fb2856fab6f26df4f20c8e7ad/Atlas.MatchingAlgorithm.Test/Services/Search/SearchRunnerTests.cs#L80)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

still missing the extra tests for asserting the new `ResultsBatched` prop on the `ResultSet<>` arg
</blockquote></details>

unit tests cannot be added here because results batched being set in results uploader


<!-- Sent from Reviewable.io -->

2023-03-24 11:24 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 3 unresolved discussions (waiting on @IgorKupreychik)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRIM41A9nOUMe3DAQ-2:-NRIM41A9nOUMe3DAQ-3:bbkicac) (no related file):*
> on call, agreed to try to commonise results uploader classes from matching, repeat and search orchestrator to a new base class within Atlas.Common.Test, and add unit tests against that new base ResultsUploader class with focus on results batching

copied here as a blocking comment

___


<!-- Sent from Reviewable.io -->

2023-03-24 12:24 UTC, zabeen requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: all files reviewed, 1 unresolved discussion (waiting on @IgorKupreychik)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRIM41A9nOUMe3DAQ-2:-NRIZk61B70liNgjoUyY:b-jmb0wf) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

> on call, agreed to try to commonise results uploader classes from matching, repeat and search orchestrator to a new base class within Atlas.Common.Test, and add unit tests against that new base ResultsUploader class with focus on results batching

copied here as a blocking comment
</blockquote></details>

this work will be done in next PR

___
___
*[`terraform/core/variables.tf` line 339 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913#-NRI9ApJ6VNBUuhKILW7:-NRIZwQ_-l_Qfh-KyJs9:b-42ngnw) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/fbe9f4688a0c74d6ad65173077c0e6e98341b8f7/terraform/core/variables.tf#L339)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

number of results written per file
</blockquote></details>

could you fix this wording pls, as you corrected it on the config readme but not here, thanks!


<!-- Sent from Reviewable.io -->

2023-03-24 12:36 UTC, zabeen approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IgorKupreychik)



<!-- Sent from Reviewable.io -->

2023-03-24 14:22 UTC, merged