905 donor import manual test cases
Anthony-Nolan/Atlas pull request #947
Opened 2023-04-18 10:51 UTC by DmitriyShcherbina

Added manual test-cases for:
- Donor Import,
- Search Request,
- Repeat Search Request

2023-04-26 10:18 UTC, zabeen requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`.DS_Store` line 0 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NTwoov4D7gYsA35PJnb:-NTwoov5CPl9UQHfmUfu:by7nn46) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3e80758f774085c16e7b3e8eab6f7ea94629bf50/.DS_Store#L0)):*
looks like this file was added to commit by accident? it would be good to remove it - let me know if you need help to do this
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NTwpmV65UpjlFqP_tPs:-NTwpmV65UpjlFqP_tPt:b-nl0ydo) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3e80758f774085c16e7b3e8eab6f7ea94629bf50/EndToEndTestCases/DonorImportManualTestCases.md#L3)):*
> ```Markdown
> # Donor Import Manual Test Cases
> 
> ## <u>Positive Scenarious</u>
> ```

typo: Scenarios
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 23 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NTwq1OR57V4qMZLPUO7:-NTwq1OR57V4qMZLPUO8:bkgkinz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3e80758f774085c16e7b3e8eab6f7ea94629bf50/EndToEndTestCases/DonorImportManualTestCases.md#L23)):*
> ```Markdown
>             "donPool": "AN",
>             "ethn": null,
>             "updateMode": "Diff",
> ```

this shouldn't be here, it should only be at top-level. I think you were using an older copy of the donor import example file, where this property was mistakenly listed as part of update body. I fixed that since. Please remove all such occurrences of `updateMode`(just leave the top-level property).



_Code quote:_
```Markdown
"updateMode": "Diff",
```


<!-- Sent from Reviewable.io -->

2023-04-26 15:38 UTC, DmitriyShcherbina reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 3 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NTwpmV65UpjlFqP_tPs:-NTyCeVO9lVuGgzpxmoO:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3e80758f774085c16e7b3e8eab6f7ea94629bf50/EndToEndTestCases/DonorImportManualTestCases.md#L3)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

typo: Scenarios
</blockquote></details>

Done.
___
*[`.DS_Store` line  at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NTwoov4D7gYsA35PJnb:-NTy9PEu5vrg7Mhrf8-9:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3e80758f774085c16e7b3e8eab6f7ea94629bf50/.DS_Store#L)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

looks like this file was added to commit by accident? it would be good to remove it - let me know if you need help to do this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-26 15:38 UTC, DmitriyShcherbina reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @zabeen)

___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 23 at r1](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NTwq1OR57V4qMZLPUO7:-NTyCpdj71ro166vP0Q0:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/3e80758f774085c16e7b3e8eab6f7ea94629bf50/EndToEndTestCases/DonorImportManualTestCases.md#L23)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

this shouldn't be here, it should only be at top-level. I think you were using an older copy of the donor import example file, where this property was mistakenly listed as part of update body. I fixed that since. Please remove all such occurrences of `updateMode`(just leave the top-level property).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-04 10:34 UTC, zabeen requested changes
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 2 of 5 files reviewed, 17 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 67 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaDPj9BNCByfoD3ZZw:-NUaCyca0FU1UyHszHcE:b-z6ziup) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L67)):*
> ```Markdown
> <br>
> 
> - Donor Import file content example (deletion mode)
> ```

please clarify that this example is for use in test clean up step
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 112 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaDudl1Jn-6f8-0dWh:-NUaDudmDRLB0dH_dlcG:b-geot6f) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L112)):*
> ```Markdown
> | 1. Upload Donor Import .json file with few donors to `donors` folder of `<env>atlasstorage`, you can use donor import file content example from Test Data section, but you should change `"recordId"`,`"changeType"` should be `"N"` (Create), donor import file name should be unique. | Donor Import file with few donors uploaded to `donors` folder of `<env>atlasstorage`|
> | 2. Run donor import function debug donor endpoint (look at test data section), use `string[]` array in it's body with donor record ids. Use in body `recordIds` used in Donor import file from step 1 | - Response code: 200 <br>`"present"` value in `"donorCounts"` object of response equals to quantity of donors in Donor import file used in step 1.<br> - Donors metadata and hla data in respose equals to donors metadata and hla data in Donor import file used in step 1. |
> |3. Delete imported donors from DB.<br>Upload donor import file in deletion mode (example in test data section) with `recordIds` uploaded in step 1|Donors uploaded in step 1 deleted from DB. |
> ```

is the intention for this step to clean the db ahead of the next test? because right now it seems like it is part of the test case itself, i.e., if deletion step failed then the entire test would fail - however, the title says this test only covers donor creation

I suggest either labelling the step as clean up/tear down, or removing it entirely
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 168 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaFiOnCAmLiiXVZ2X-:-NUaFiOnCAmLiiXVZ2X0:b-jhmrqz) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L168)):*
> ```Markdown
> | Test step | Expected Result |
> | --------- | --------------- |
> | 1. Upload Donor Import .json file with few donors to `donors` folder of `<env>atlasstorage`, you can use donor import file content example from Test Data section, but you should change `"recordId"`(<b>you should use recordIds of donors that exist in the db</b>),`"changeType"` should be `"D"` (Delete), donor import file name should be unique. | Donor Import file with few donors uploaded to `donors` folder of `<env>atlasstorage`|
> ```

You could copy the instructions for finding such donors from step 1 of test case 3 (`NU`)



_Code quote:_
```Markdown
you should use recordIds of donors that exist in the db
```
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 174 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaFImTBCHhO-JEjwHt:-NUaFImTBCHhO-JEjwHu:bq7fy1u) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L174)):*
> ```Markdown
> <br></br>
> 
> ### 3. Donor Import [`Create or Update`] when some donors in import file should be created and some of them shoul be updated (they exist in DB)
> ```

typo: should



_Code quote:_
```Markdown
 shoul be updated (t
```
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 283 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaGdTx3_2ikKyxAPM5:-NUaGdTx3_2ikKyxAPM6:b-vaj28g) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L283)):*
> ```Markdown
> | 1. Select one or few donors in `<env>atlas` DB, `Donors.Donors` table:<br> - Note it/theirs `ExternalDonorCode` values and HLA data | - `ExternalDonorCode` of one or few donors noted.<br> - HLA data for this donor/donors noted |
> | 2. Upload Donor Import .json file with some donors to `donors` folder of `<env>atlasstorage`, you can use donor import file content example from Test Data section, but you should change `"recordId"`:<br> - One or few of donors should exist in DB, you should use `ExternalDonorCode` noted in step 1 as `"recordId"` for this donor/donors (<b>HLA data in Donor Import file for this donors should be different from noted in step 1</b> - to check that HLA data in DB could be updated)<br> - Rest few donors and their `"recordId"` should be unique.<br> - `"changeType"` should be `"NU"` (Create or Update), donor import file name should be unique. | Donor Import file with few donors uploaded to `donors` folder of `<env>atlasstorage`|
> | 3. Run donor import function debug donor endpoint (look at test data section), use `string[]` array in it's body with donor record ids. Use in body `recordIds` used in Donor import file from step 2 | - Response code: 200 <br> - `"present"` value in `"donorCounts"` object of response equals to quantity of donors in Donor import file used in step 1.<br> - Donors metadata and hla data in respose equals to donors metadata and hla data in Donor import file used in step 2. |
> ```

typo: response



_Code quote:_
```Markdown
hla data in respose equals to
```
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 284 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaGmReDR5JwgZgg3N8:-NUaGmReDR5JwgZgg3N9:basc42s) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L284)):*
> ```Markdown
> | 2. Upload Donor Import .json file with some donors to `donors` folder of `<env>atlasstorage`, you can use donor import file content example from Test Data section, but you should change `"recordId"`:<br> - One or few of donors should exist in DB, you should use `ExternalDonorCode` noted in step 1 as `"recordId"` for this donor/donors (<b>HLA data in Donor Import file for this donors should be different from noted in step 1</b> - to check that HLA data in DB could be updated)<br> - Rest few donors and their `"recordId"` should be unique.<br> - `"changeType"` should be `"NU"` (Create or Update), donor import file name should be unique. | Donor Import file with few donors uploaded to `donors` folder of `<env>atlasstorage`|
> | 3. Run donor import function debug donor endpoint (look at test data section), use `string[]` array in it's body with donor record ids. Use in body `recordIds` used in Donor import file from step 2 | - Response code: 200 <br> - `"present"` value in `"donorCounts"` object of response equals to quantity of donors in Donor import file used in step 1.<br> - Donors metadata and hla data in respose equals to donors metadata and hla data in Donor import file used in step 2. |
> |4. Check updated donors HLA data in `<env>atlas` DB:<br> - `ExternalDonorCode` from step 1 and find donors.<br> - Compare their HLA data in DB to HLA data in uploaded Donor Import file in step 2. | Updated donors HLA data in DB mathes HLA data used in Donor Import file from step 2. |
> ```

typo: matches
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 284 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaGthRDDRBozjPFUe7:-NUaGthRDDRBozjPFUe8:b-n1ln0w) ([raw file](https://github.com/Anthony-Nolan/At [...]

2023-05-04 10:36 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 2 of 5 files reviewed, 18 unresolved discussions (waiting on @DmitriyShcherbina)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaJzqg0s5Bm95ZrTzw:-NTx3TIG3FjxQGraDCls:b-unixbp) (no related file):*
@DmitriyShcherbina - would it be helpful to add a new debug endpoint for finding existing donors in the atlas donor store, so QA doesn't have to go into the db? e.g., `GetTop100Donors` - could have `donorType` and `registry` as optional query parameters

___


<!-- Sent from Reviewable.io -->

2023-05-04 13:43 UTC, zabeen reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 2 of 5 files reviewed, 18 unresolved discussions (waiting on @DmitriyShcherbina)



<!-- Sent from Reviewable.io -->

2023-05-05 18:42 UTC, zabeen reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 2 of 5 files reviewed, 19 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 1 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUgCpk3-HhUocInrjxK:-NUgCpk3-HhUocInrjxL:b9w0sbq) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L1)):*
> ```Markdown
> # Donor Import Manual Test Cases
> ```

typo: title should be Repeat Search


<!-- Sent from Reviewable.io -->

2023-05-22 17:09 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 2 of 5 files reviewed, 29 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 5 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3Qe-oDEDxVeuMz6qG:-NW3Qe-oDEDxVeuMz6qH:b-63ezpm) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L5)):*
> ```Markdown
> ## <u>Positive Scenarios</u>
> 
> ### 1. Repeat Search Request (10/10 - no mismatch, batching: off)
> ```

This test only looks for newly added donors, but repeat search also reports deleted/no longer matching donors

So recommend extending the name to reflect that, e.g., "Repeat Search Request for newly matched donors"



_Code quote:_
```Markdown
Repeat Search Request (10/10 - no mismatch, batching: off)
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 11 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3OQ8R23ESWHBhoMaX:-NW3OQ8R23ESWHBhoMaY:bt5sn9a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L11)):*
> ```Markdown
> <b>Preconditions:</b><br>Repeat Search results shouldn't be batched:<br>
> `<ENV>-ATLAS-REPEAT-SEARCH-FUNCTIONS` AzureStorage:SearchResultsBatchSize: `0`<br>
> `<ENV>-ATLAS-FUNCTIONS` AtlasFunction:AzureStorage:ShouldBatchResuls: `False`
> ```

typo: ShouldBatchResults



_Code quote:_
```Markdown
ShouldBatchResuls
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 135 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3OjeRCEh5j2DtMvsm:-NW3OjeSB8snwoxW1fa4:b5005jg) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L135)):*
> ```Markdown
> 
> ```
> POST https://dev-atlas-api.azurewebsites.net/api/RepeatSearch
> ```

replace with `<env>-atlas`



_Code quote:_
```Markdown
/dev-atlas
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 195 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3POqgE4NahwONxM-6:-NW3POqgE4NahwONxM-7:b-zbsuj4) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L195)):*
> ```Markdown
> | 1. Run Search Request, but set in request body:<br> - `"DonorMismatchCount"` value to `0`<br> - All HLA mismatch values in `"LocusMismatchCriteria"` should be `0`<br> - Note `searchIdentifier` from request response | - Result code: 200.<br> - `searchIdentifier` in request response: has `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` format.<br> - `searchIdentifier` from request response noted |
> | 2. Upload Donor Import .json file with few donors to `donors` folder of `<env>atlasstorage`, you can use donor import file content example from Test Data section, but you should change `"recordId"`,`"changeType"` should be `"NU"` (Create or Update), donor import file name should be unique. | Donor Import file with few donors uploaded to `donors` folder of `<env>atlasstorage`|
> | 3. Run Repeat Search Request, but set in request body:<br> - `"OriginalSearchId"` value to `searchIdentifier` value, noted in step 1. <br> - `"SearchCutoffDate"` value to today's date in format `"YYYY-MM-DD"`(in order to show in results only donors that were imported today).<br> - All HLA mismatch values in `"LocusMismatchCriteria"` should be `0`<br> - Note `searchIdentifier` from request response | - Result code: 200.<br> - `searchIdentifier` in request response: has `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` format.<br> - `repeatSerchIdentifier` in request response: has `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` format. |
> ```

Replace with "- `SearchRequest` should be copied from the request body of the search submitted in step 1"



_Code quote:_
```Markdown
- All HLA mismatch values in `"LocusMismatchCriteria"` should be `0`
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 196 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3Pr9W--gqjl_jhMZu:-NW3Pr9W--gqjl_jhMZv:bp5a6p5) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L196)):*
> ```Markdown
> | 2. Upload Donor Import .json file with few donors to `donors` folder of `<env>atlasstorage`, you can use donor import file content example from Test Data section, but you should change `"recordId"`,`"changeType"` should be `"NU"` (Create or Update), donor import file name should be unique. | Donor Import file with few donors uploaded to `donors` folder of `<env>atlasstorage`|
> | 3. Run Repeat Search Request, but set in request body:<br> - `"OriginalSearchId"` value to `searchIdentifier` value, noted in step 1. <br> - `"SearchCutoffDate"` value to today's date in format `"YYYY-MM-DD"`(in order to show in results only donors that were imported today).<br> - All HLA mismatch values in `"LocusMismatchCriteria"` should be `0`<br> - Note `searchIdentifier` from request response | - Result code: 200.<br> - `searchIdentifier` in request response: has `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` format.<br> - `repeatSerchIdentifier` in request response: has `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx` format. |
> | 3. Check Repeat Search results in `<env>atlasstorage`: `repeat-search-results` blob container (use `searchIdentifier` from step 1) | - There is a folder with name equal to `searchIdentifier` from step 1 in `repeat-search-results`.<br> - There is a .json file with name equal to `repeatSearchIdentifier` from step 3.<br> - This file contains donors imported in step 2 in `Results` list.|
> ```

typo: 4.



_Code quote:_
```Markdown
3.
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 201 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3R16O3Oj9x2WG1C3F:-NW3R16O3Oj9x2WG1C3G:b-seggf) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L201)):*
> ```Markdown
> <br></br>
> 
> ### 2. Repeat Search Request (10/10 - no mismatch, batching: on)
> ```

as above, "Repeat Search Request for newly matched donors"



_Code quote:_
```Markdown
Repeat Search Request (10/10 - no mismatch, batching: on)
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 207 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3PxC286ILZKsxmZYy:-NW3PxC286ILZKsxmZYz:bt5sn9a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L207)):*
> ```Markdown
> <b>Preconditions:</b><br>Repeat Search results shouldn't be batched:<br>
> `<ENV>-ATLAS-REPEAT-SEARCH-FUNCTIONS` AzureStorage:SearchResultsBatchSize: `2`<br>
> `<ENV>-ATLAS-FUNCTIONS` AtlasFunction:AzureStorage:ShouldBatchResuls: `True`
> ```

typo: ShouldBatchResults



_Code quote:_
```Markdown
ShouldBatchResuls
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 331 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3QxAvEi_lqbykbSNJ:-NW3QxAvEi_lqbykbSNK:b-jq408q) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L331)):*
> ```Markdown
> 
> ```
> POST https://dev-atlas-api.azurewebsites.net/api/RepeatSearch
> ```

<env>-atlas



_Code quote:_
```Markdown
dev-atlas
```
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 391 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3QCp3AJts-vQveuN0:-NW3QCp3AJts-vQveuN1:b-5aw5xi) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L391)):*
> ```Markdown
> | 1. Run Search Request, but set in request body:<br> -  [...]

2023-05-22 17:31 UTC, zabeen reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 3 of 5 files reviewed, 30 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/SearchManualTestCases.md` line 1 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3S2p2-QcGYlDydwtD:-NW3S2p2-QcGYlDydwtE:b-ogb0d3) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SearchManualTestCases.md#L1)):*
> ```Markdown
> # Donor Import Manual Test Cases
> ```

typo: rename to search manual test cases



_Code quote:_
```Markdown
 Donor Import Manual Test Cases
```


<!-- Sent from Reviewable.io -->

2023-05-22 18:11 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 4 of 5 files reviewed, 46 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 33 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3cufd-jZjgJlSadxn:-NW3cufd-jZjgJlSadxo:b-8tb4lo) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L33)):*
> ```Markdown
> | Test step | Expected Result |
> | --------- | --------------- |
> | 1. Upload donor-id-checker request file to `donors/donor-id-checker/requests` directory of `devatlasstorage`.<br> Uploaded file should have <b>unique name</b> and contain:<br> - `"donPool"` value equal to specific registry (e.g. `"AN"` or `"GB"`),<br> - `"donors"` list should contain same set of donor ids as presented in DB for specific registry defined in `"donPool"` parameter. | Donor-id-checker request file uploaded to `donors/donor-id-checker/requests` directory of `devatlasstorage` |
> ```

step 2 to check `donors/donor-id-checker/requests` for new message seems to be missing from this table (it is present in the next test)
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 34 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3cNv5CjFkoHATSC0q:-NW3cNv5CjFkoHATSC0r:b-28zq9l) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L34)):*
> ```Markdown
> | --------- | --------------- |
> | 1. Upload donor-id-checker request file to `donors/donor-id-checker/requests` directory of `devatlasstorage`.<br> Uploaded file should have <b>unique name</b> and contain:<br> - `"donPool"` value equal to specific registry (e.g. `"AN"` or `"GB"`),<br> - `"donors"` list should contain same set of donor ids as presented in DB for specific registry defined in `"donPool"` parameter. | Donor-id-checker request file uploaded to `donors/donor-id-checker/requests` directory of `devatlasstorage` |
> | 2. Check `donor-id-checker-results` topic of `dev-atlas` service bus | - No new deadlettered messages,<br> - There is a new message which contain: `"RequestFileLocation"` value with uploaded file filename, `"ResultsCount"` (should be `0`) and `"ResultsFilename"` (should be empty - `""`) |
> ```

Would remove this check, as messages can only be dead-lettered by a consumer



_Code quote:_
```Markdown
- No new deadlettered messages,
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 34 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3caS8-2_IAWLN3RO3:-NW3caS8-2_IAWLN3RO4:b-5fket6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L34)):*
> ```Markdown
> | --------- | --------------- |
> | 1. Upload donor-id-checker request file to `donors/donor-id-checker/requests` directory of `devatlasstorage`.<br> Uploaded file should have <b>unique name</b> and contain:<br> - `"donPool"` value equal to specific registry (e.g. `"AN"` or `"GB"`),<br> - `"donors"` list should contain same set of donor ids as presented in DB for specific registry defined in `"donPool"` parameter. | Donor-id-checker request file uploaded to `donors/donor-id-checker/requests` directory of `devatlasstorage` |
> | 2. Check `donor-id-checker-results` topic of `dev-atlas` service bus | - No new deadlettered messages,<br> - There is a new message which contain: `"RequestFileLocation"` value with uploaded file filename, `"ResultsCount"` (should be `0`) and `"ResultsFilename"` (should be empty - `""`) |
> ```

Check `audit` subscription of `donor-id-checker-results` topic 



_Code quote:_
```Markdown
Check `donor-id-checker-results` topic 
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 68 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3dDbh3aBW0mgZ-Xe1:-NW3dDbh3aBW0mgZ-Xe2:b-5fket6) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L68)):*
> ```Markdown
> | --------- | --------------- |
> | 1. Upload donor-id-checker request file to `donors/donor-id-checker/requests` directory of `devatlasstorage`.<br> Uploaded file should have <b>unique name</b> and contain:<br> - `"donPool"` value equal to specific registry (e.g. `"AN"` or `"GB"`),<br> - `"donors"` list should contain same set of donor ids as presented in DB for specific registry defined in `"donPool"` parameter and <b>have few additional donor ids</b> which absent in DB | Donor-id-checker request file uploaded to `donors/donor-id-checker/requests` directory of `devatlasstorage` |
> | 2. Check `donors/donor-id-checker/requests` topic of `dev-atlas` service bus | - No new deadlettered messages,<br> - There is a new message which contain: `"RequestFileLocation"` value with uploaded file filename, `"ResultsCount"` and `"ResultsFilename"` |
> ```

Check `audit` subscription of `donor-id-checker-results` topic 



_Code quote:_
```Markdown
Check `donors/donor-id-checker/requests` topic
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 69 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3de9w7ww1uAQM84tX:-NW3de9w7ww1uAQM84tY:ba54j06) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L69)):*
> ```Markdown
> | 1. Upload donor-id-checker request file to `donors/donor-id-checker/requests` directory of `devatlasstorage`.<br> Uploaded file should have <b>unique name</b> and contain:<br> - `"donPool"` value equal to specific registry (e.g. `"AN"` or `"GB"`),<br> - `"donors"` list should contain same set of donor ids as presented in DB for specific registry defined in `"donPool"` parameter and <b>have few additional donor ids</b> which absent in DB | Donor-id-checker request file uploaded to `donors/donor-id-checker/requests` directory of `devatlasstorage` |
> | 2. Check `donors/donor-id-checker/requests` topic of `dev-atlas` service bus | - No new deadlettered messages,<br> - There is a new message which contain: `"RequestFileLocation"` value with uploaded file filename, `"ResultsCount"` and `"ResultsFilename"` |
> | 3. Check processing result file in `donors/donor-id-checker/requests` directory of `devatlasstorage`<br> - To identify needed file you could use `"ResultsFilename"` from previous step | - Result file presents in `donors/donor-id-checker/requests` directory of `devatlasstorage`<br> - `"AbsentRecordIds"` list contains donor ids which are missing in DB but present in uploaded donor-id-checker request file |
> ```

should be `results` container



_Code quote:_
```Markdown
`donors/donor-id-checker/requests`
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 70 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3dkR9B-Q4x8l0AR7T:-NW3dkR9B-Q4x8l0AR7U:bcr4qrh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L70)):*
> ```Markdown
> | 2. Check `donors/donor-id-checker/requests` topic of `dev-atlas` service bus | - No new deadlettered messages,<br> - There is a new message which contain: `"RequestFileLocation"` value with uploaded file filename, `"ResultsCount"` and `"ResultsFilename"` |
> | 3. Check processing result file in `donors/donor-id-checker/requests` directory of `devatlasstorage`<br> - To identify needed file you could use `"ResultsFilename"` from previous step | - Result file presents in `donors/donor-id-checker/requests` directory of `devatlasstorage`<br> - `"AbsentRecordIds"` list contains donor ids which are missing in DB but present in uploaded donor-id-checker request file |
> ---
> ```

Ad [...]

2023-05-22 18:11 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 4 of 5 files reviewed, 46 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 68 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3dDbh3aBW0mgZ-Xe1:-NW3eE5A0wjHdPbisBzr:bfwq1d8) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L68)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Check `audit` subscription of `donor-id-checker-results` topic 
</blockquote></details>

correction: "Check `audit` subscription of `donor-id-checker-requests` topic"


<!-- Sent from Reviewable.io -->

2023-05-23 10:57 UTC, zabeen requested changes
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 4 of 5 files reviewed, 55 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 1 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7Bv6sAVi9wRsEjsqI:-NW7Bv6sAVi9wRsEjsqJ:b-nowah3) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L1)):*
> ```Markdown
> # Symmetric Difference Manual Test Cases
> ```

This file has similar set of issues across test cases, probably because they have been copied/pasted to make things quicker. So I am summarising here, please go through the test cases and fix any typos, thanks

Every test should have following steps:
1) Upload file to `requests` container on blob storage
2) Check `audit` sub of `requests` topic (no new dead-letters and a new message with the uploaded file name)
3) After few minutes, check `audit` sub of `results` topic (check for new message, but not dead-letters, and new message should have results count and if count > 0, a results file name)
4) If results file written, check file within `results` container of blob storage, for values of absent records ids and orphaned record ids, as required
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 74 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW79XLQ-iwQaXKi5PX_:-NW79XLQ-iwQaXKi5PXa:b-piqhuu) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L74)):*
> ```Markdown
> <br></br>
> 
> ### 3. Uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors
> ```

I would reword this to better reflect the intent of the feature.

"Atlas set of donors has additional donor ids when compared to uploaded donor-id-checker request file"



_Code quote:_
```Markdown
 Uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 76 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7BKMe30ovwskhPDr9:-NW7BKMe30ovwskhPDrA:b8ayw3a) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L76)):*
> ```Markdown
> ### 3. Uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors
> 
> <b>Description:</b> Check that result of submitted file processing, in case when uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors (in DB), return 0 absent donor records (don't exist in DB) and X orphaned donor records (don't exist in submitted file)
> ```

when Atlas set of donors (in DB) has additional donor ids compared to uploaded donor-id-checker request file



_Code quote:_
```Markdown
when uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors (in DB)
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 109 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7DDfA4LMSl6Ray_v3:-NW7DDfA4LMSl6Ray_v4:bml0hxj) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L109)):*
> ```Markdown
> <br></br>
> 
> ### 4. Uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors but Atlas set of donors also has missing donor ids comparing to uploaded donor-id-checker request file
> ```

As above, recommend rewording:

"Atlas set of donors has missing donor ids AND additional donor ids when compared to uploaded donor-id-checker request file"



_Code quote:_
```Markdown
Uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors but Atlas set of donors also has missing donor ids comparing to uploaded donor-id-checker request file
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 111 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7DTS94v0zOFbOIGA3:-NW7DTS94v0zOFbOIGA4:bbcfhgx) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L111)):*
> ```Markdown
> ### 4. Uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors but Atlas set of donors also has missing donor ids comparing to uploaded donor-id-checker request file
> 
> <b>Description:</b> Check that result of submitted file processing, in case when uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors (in DB) but Atlas set of donors also has missing donor ids comparing to uploaded donor-id-checker request file, return X absent donor records (don't exist in DB) and X orphaned donor records (don't exist in submitted file)
> ```

when Atlas set of donors (in DB) has missing donor ids AND additional donor ids compared to uploaded donor-id-checker request file



_Code quote:_
```Markdown
when uploaded donor-id-checker request file has missing donor ids comparing to Atlas set of donors (in DB) but Atlas set of donors also has missing donor ids comparing to uploaded donor-id-checker request file
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 213 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7E8f3DE2cEbc5x-Yi:-NW7E8f3DE2cEbc5x-Yj:bewqkak) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L213)):*
> ```Markdown
> <br></br>
> 
> ### 7. Atlas set of donors has missing donor ids comparing to uploaded donor-id-checker request file, donor-id-checker request file contain unrequired "checkingMode" parameter
> ```

I would simplify this to highlight the intent of the test, which is to make sure `checkingMode` property doesn't cause problems

"Uploaded donor-id-checker request file contains unrequired "checkingMode" property"



_Code quote:_
```Markdown
Atlas set of donors has missing donor ids comparing to uploaded donor-id-checker request file, donor-id-checker request file contain unrequired "checkingMode" parameter
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 215 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7EUw41-ej94bN4CK3:-NW7EUw41-ej94bN4CK4:b4ul8lh) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L215)):*
> ```Markdown
> ### 7. Atlas set of donors has missing donor ids comparing to uploaded donor-id-checker request file, donor-id-checker request file contain unrequired "checkingMode" parameter
> 
> <b>Description:</b> Check that result of submitted file processing, in case when Atlas set of donors (in DB) has missing donor ids comparing to uploaded donor-id-checker request file and donor-id-checker request file contain unrequired "checkingMode" parameter, return X absent donor records (don't exist in DB) and 0 orphaned donor records (don't exist in submitted file)
> ```

can remove this



_Code quote:_
```Markdown
when Atlas set of donors (in DB) has missing donor ids comparing to uploaded donor-id-checker request file and 
```
___
*[`EndToEndTestCases/SymmetricDifferenceManualTestCases.md` line 215 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW7EaJz4AjItsiT0TpJ:-NW7EaJz4AjItsiT0TpK:b-bt3cpp) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/SymmetricDifferenceManualTestCases.md#L215)):*
> ```Markdown
> ### 7. Atlas set of donors has missing donor ids comparing to uploaded donor-id-checker request file, donor-id-checker requ [...]

2023-05-23 10:58 UTC, zabeen reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: all files reviewed, 55 unresolved discussions (waiting on @DmitriyShcherbina)



<!-- Sent from Reviewable.io -->

2023-05-24 14:41 UTC, DmitriyShcherbina reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 1 of 5 files reviewed, 43 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaJzqg0s5Bm95ZrTzw:-NWCBc5G-CE_3AK1hiFx:bf8k2dr) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

@DmitriyShcherbina - would it be helpful to add a new debug endpoint for finding existing donors in the atlas donor store, so QA doesn't have to go into the db? e.g., `GetTop100Donors` - could have `donorType` and `registry` as optional query parameters
</blockquote></details>

Hm, it's good idea as for me. Could be very helpful!

___
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 67 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaDPj9BNCByfoD3ZZw:-NWCClrH6wTBqYfrewSK:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L67)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

please clarify that this example is for use in test clean up step
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 112 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaDudl1Jn-6f8-0dWh:-NWCDhp07q7JbYVfYs59:b-we0m83) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L112)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

is the intention for this step to clean the db ahead of the next test? because right now it seems like it is part of the test case itself, i.e., if deletion step failed then the entire test would fail - however, the title says this test only covers donor creation

I suggest either labelling the step as clean up/tear down, or removing it entirely


</blockquote></details>

Deletion step here was added according to comment from Daria to clean up donors added to db in testing purpose. I've added [Clean Up] label to this step, but if you think that this step is unnecessary here - we could just delete it.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 168 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaFiOnCAmLiiXVZ2X-:-NWCGK0l6ETAeUmEIfo1:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L168)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

You could copy the instructions for finding such donors from step 1 of test case 3 (`NU`)
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 284 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaGthRDDRBozjPFUe7:-NWCHOTC-CqSXBQxCMTo:b-tdevdd) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L284)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

is step 4 needed? the debug endpoint shows the HLA so tester doesn't have to go into db to check if it has been updated
</blockquote></details>

You're right, step 4 is redundant here.
I've deleted it from this test-case.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 285 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaH7i78SzBmVZ4BC1X:-NWCLDpb4qNUJxgc8BCd:b-qdf1ah) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L285)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

as above, pls either label as test clean up/tear down, or remove step
</blockquote></details>

I've added [Clean Up] label to this step, but if you think that this step is unnecessary here - we could just delete it.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 398 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaHf_wEb_e-lzmqZlw:-NWCMGv-DUGpuMB6LGw9:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L398)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

add instructions for finding an existing donor
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 400 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaHu2J3SQQxp4uTVAs:-NWCvB5x9yLlauWS4l6K:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L400)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Recommend some more instructions here, e.g., "Go to Atlas Application Insights Logs (`<ENV>-ATLAS`) within Azure web portal and check donor import logs:"

I would also paste in the actual AI query if you have it saved
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 401 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaIiQ1DFjXEQfL7X7z:-NWCxK573WlY7TW3F4B2:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L401)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

as above, pls label as teardown or remove, thanks
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 401 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaJHdW7S5r4uQ5KZhp:-NWCxmbgDoFiJseKraEn:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L401)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Extra test step: Check the `alerts` topic on `<env>-atlas` service bus: there should **not** be an alert message for this import file.
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 456 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaJ4EFDc62QSW3ONDP:-NWCyQ4c32wiEb74bbCu:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L456)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

pls add instructions for how to find existing donors
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 457 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaJm6Z0X077-PwAb7D:-NWCyi7p0fe5dTqIv7gs:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/DonorImportManualTestCases.md#L457)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Extra test steps: 
- Check AI logs for import failure
- Check the `alerts` topic on `<env>-atlas` service bus: there should **not** be an alert message for this import file.
</blockquote></details>

Done.
___
*[`EndToEndTestCases/RepeatSearchManualTestCases.md` line 5 at r2](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NW3Qe-oDEDxVeuMz6qG:-NWCzCNh5SpsCmynEQ7U:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/758e6daa209695c9d960ad8f2b7cf5dbcbb2b3e3/EndToEndTestCases/RepeatSearchManualTestCases.md#L5)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

This test only looks for newly added donors, but repeat search also  [...]

2023-07-10 10:22 UTC, zabeen requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 1 of 5 files reviewed, 43 unresolved discussions (waiting on @DmitriyShcherbina)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NZzJYsh1HEJAdsXCE7g:-NZzJYsh1HEJAdsXCE7h:b-eeqwpi) (no related file):*
As discussed on call, please remove "ManualTestCases" from file names.

___
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 67 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NWmQcSJ2I60SG2IJlgt:-NWmQcSJ2I60SG2IJlgu:bd60pdo) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/52da23371bc2ce79504df4783f37451c793a8520/EndToEndTestCases/DonorImportManualTestCases.md#L67)):*
> ```Markdown
> <br>
> 
> - Donor Import file content example (deletion mode), should be used in step 3 for added in this test donors deletion
> ```

should be use in step 3 for deletion of test donors added during this test



_Code quote:_
```Markdown
should be used in step 3 for added in this test donors deletion
```


<!-- Sent from Reviewable.io -->

2023-07-12 10:39 UTC, DmitriyShcherbina reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 1 of 6 files reviewed, 44 unresolved discussions (waiting on @zabeen)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NZzJYsh1HEJAdsXCE7g:-N_8dTCI4OwM9tirpWW2:b-896fix) (no related file):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

As discussed on call, please remove "ManualTestCases" from file names.
</blockquote></details>

Done.

___
___
*[`EndToEndTestCases/DonorImport.md` line 288 at r4](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-N_8XY4LBOq6DlHlZgQj:-N_8f37S4tbYCivTdFc3:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/f93fd87fe2c647dfb1600bb7155f3202bbdbd1f4/EndToEndTestCases/DonorImport.md#L288)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

Please extend the relevant negative scenarios with test step of checking the new table, `Donors.DonorImportFailures`, for a new row(s) listing the failed donor updates.
</blockquote></details>

Done.
___
*[`EndToEndTestCases/DonorImportManualTestCases.md` line 67 at r3](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NWmQcSJ2I60SG2IJlgt:-N_8dnFQ6jFs1CoaSVqO:b-896fix) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/52da23371bc2ce79504df4783f37451c793a8520/EndToEndTestCases/DonorImportManualTestCases.md#L67)):*
<details><summary><i>Previously, zabeen (Dr Zabeen Patel) wrote…</i></summary><blockquote>

should be use in step 3 for deletion of test donors added during this test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-04 20:39 UTC, zabeen requested changes
> Reviewed 1 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @DmitriyShcherbina)

___
*[`EndToEndTestCases/RepeatSearch.md` line 1 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NkqVbLWCIz3osMLGgGZ:-NkqVbLWCIz3osMLGgG_:b-2m4y6l) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5910fc6fd97109d4844972b2060063b53b3fad9f/EndToEndTestCases/RepeatSearch.md#L1)):*
> ```Markdown
> # Donor Repeat Search Test Cases
> ```

Please remove word "Donor"



_Code quote:_
```Markdown
Donor
```
___
*[`EndToEndTestCases/Search.md` line 1 at r5](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NkqVvuO-q1xCB8_IZkp:-NkqVvuO-q1xCB8_IZkq:b-2m4y6l) ([raw file](https://github.com/Anthony-Nolan/Atlas/blob/5910fc6fd97109d4844972b2060063b53b3fad9f/EndToEndTestCases/Search.md#L1)):*
> ```Markdown
> # Donor Search Test Cases
> ```

Please remove word "Donor"



_Code quote:_
```Markdown
Donor 
```


<!-- Sent from Reviewable.io -->

2023-12-05 09:47 UTC, zabeen reviewed
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @DmitriyShcherbina)

*[a discussion](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947#-NUaJzqg0s5Bm95ZrTzw:-NktN-Za8fhD1zSpU26l:b-7auzri) (no related file):*
<details><summary><i>Previously, DmitriyShcherbina (Dmitriy) wrote…</i></summary><blockquote>

Hm, it's good idea as for me. Could be very helpful!
</blockquote></details>

Done: https://github.com/Anthony-Nolan/Atlas/issues/1144#issuecomment-1840398037

___


<!-- Sent from Reviewable.io -->

2023-12-05 20:43 UTC, zabeen reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Anthony-Nolan/Atlas/947)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @DmitriyShcherbina)



<!-- Sent from Reviewable.io -->

2024-01-10 20:22 UTC, closed without merging

2024-01-10 20:23 UTC, zabeen commented
Closed PR as it has been replaced with 2 more PRs.